# Generated by Django 3.1 on 2020-08-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('about', models.TextField()),
                ('skills', models.TextField()),
                ('image', models.ImageField(upload_to='images/myimage')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phoneNo', models.IntegerField()),
                ('message', models.TextField()),
                ('header', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='images/myimage')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
