# Generated by Django 3.1 on 2020-08-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='image',
            new_name='profile_image',
        ),
    ]
