# Generated by Django 3.1 on 2020-08-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200816_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='profile_image',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
