# Generated by Django 3.0.5 on 2020-08-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200816_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='logo',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
