# Generated by Django 3.0.5 on 2020-08-27 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_aboutme_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='logo',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='my_logo',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
