# Generated by Django 3.1 on 2020-08-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200827_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='my_logo',
        ),
    ]
