# Generated by Django 3.1 on 2020-08-27 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_aboutme_my_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='my_logo',
            field=models.TextField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
