# Generated by Django 3.1 on 2020-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_aboutme_my_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='my_logo',
            field=models.CharField(max_length=10),
        ),
    ]
