# Generated by Django 3.1 on 2020-09-04 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200827_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='cV',
            field=models.FileField(default=django.utils.timezone.now, upload_to='CVfolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='skills',
            field=models.TextField(max_length=500),
        ),
    ]
