# Generated by Django 3.1 on 2020-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200904_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Social media Links', max_length=20)),
                ('facebook', models.URLField(blank=True, max_length=300)),
                ('github', models.URLField(blank=True, max_length=300)),
                ('twitter', models.URLField(blank=True, max_length=300)),
                ('instagram', models.URLField(blank=True, max_length=300)),
                ('linkedLn', models.URLField(blank=True, max_length=300)),
            ],
        ),
    ]
