# Generated by Django 3.1 on 2020-09-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_social_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Link',
            new_name='SocialLink',
        ),
    ]
