# Generated by Django 3.1 on 2020-09-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200904_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='name',
        ),
    ]
